services:
  db:
    ports:
      - "27017:27017"
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: bot
  bot:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      ENVIRONMENT: "development"
      ADDRESS: "mongodb://db:27017"